version: "3"

services:

  frontend:
    build:
      context: ./todoClient
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - backend
  backend:
    build:
      context: ./todoServer
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - database
    volumes:
      - ./todoServer/.env:/app/.env
  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_PASSWORD=password
